color0 #291e14
color1 #e7842d
color2 #eda15f
color3 #eae548
color4 #9eea48
color5 #f2bc8c
color6 #f2ef8d
color7 #f3f2f2
color8 #73685e
color9 #e7842d
color10 #eda15f
color11 #eae548
color12 #9eea48
color13 #f2bc8c
color14 #f2ef8d
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291e14
background            #291e14
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #37281b
active_border_color   #eda15f
inactive_border_color #37281b
url_color             #eda15f

active_tab_foreground   #251e18
active_tab_background   #eda15f
inactive_tab_foreground #b6b2af
inactive_tab_background #37281b
cursor_trail_color      #b6b2af
