color0 #070736
color1 #fd4663
color2 #6261ea
color3 #9e52e8
color4 #e852e7
color5 #8f8ef0
color6 #c08ef0
color7 #f2f2f3
color8 #5e5e72
color9 #fd4663
color10 #6261ea
color11 #9e52e8
color12 #e852e7
color13 #8f8ef0
color14 #c08ef0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #070736
background            #070736
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #0a0a48
active_border_color   #6261ea
inactive_border_color #0a0a48
url_color             #6261ea

active_tab_foreground   #191825
active_tab_background   #6261ea
inactive_tab_foreground #afafb6
inactive_tab_background #0a0a48
cursor_trail_color      #afafb6
