# ==============================================================================
# Configuração Pessoal do Kitty (MyNixOs)
# ==============================================================================

# Importa as cores geradas dinamicamente pela Noctalia Shell
include themes/noctalia.conf

# Estilo e Fontes
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        12.0

# Janela e Transparência
window_padding_width 12
background_opacity 0.90

# Estilo de Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Permitir controle remoto de cores (para live reload)
allow_remote_control yes


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME