[colors.primary]
background = '#292714'
foreground = '#f3f3f2'
 
[colors.cursor]
text = '#f3f3f2'
cursor = '#b6b6af' 
 
[colors.vi_mode_cursor]
text = '#292714'
cursor = '#e9dc62' 
 
[colors.search.matches]
foreground = '#37341b' 
background = '#5be64c' 
 
[colors.search.focused_match]
foreground = '#37341b' 
background = '#e9dc62' 
 
[colors.footer_bar]
foreground = '#37341b' 
background = '#e8e7e3' 
 
[colors.hints.start]
foreground = '#37341b' 
background = '#a8e64c' 
 
[colors.hints.end]
foreground = '#37341b' 
background = '#a8e64c' 
 
[colors.selection]
text = '#292714'
background = '#e9dc62'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#e9dc62' 
yellow = '#a49828' 
blue = '#e9dc62' 
magenta = '#5be64c' 
cyan = '#a8e64c' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 